### ISSUE TITLE
Cannot clone on Windows Git

### ISSUE THREAD

**Issue by iMartyn** [open-mmlab/mmediting#70]
The choice of folder structure appears to be the problem here :
```
Martyn@i9top MINGW64 ~/Documents/src/github.com/open-mmlab
$ git clone https://github.com/open-mmlab/mmsr.git
Cloning into 'mmsr'...
remote: Enumerating objects: 130, done.
remote: Total 130 (delta 0), reused 0 (delta 0), pack-reused 130
Receiving objects: 100% (130/130), 96.33 KiB | 334.00 KiB/s, done.
Resolving deltas: 100% (40/40), done.
error: invalid path 'experiments/pretrained_models/Put pretrained models here.'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

I've tried manually creating that folder, doing lots of git tricks but to no avail, no way using Windows Git (`git version 2.26.2.windows.1`) to get the repo cloned from github. I think git for windows simply cannot handle a folder ending in a period.

Same via ssh btw, I just picked the https logs.

**Comment by besit** [comment]
This helped me:
1) open command prompt and go to the folder you have cloned to
2) run `git reset`
3) run `git checkout *`

Hope this will help you too

**Comment by CauchyHu** [comment]
I've tried your solution, but this problem have not resolved.

**Comment by besit** [comment]
> I've tried your solution, but this problem have not resolved.

Try to download the archive and just unpack it into a folder

**Comment by iMartyn** [comment]
What?! Why are you closing this?  This is still a problem, and "download the zip" is not an acceptable answer.

**Comment by CauchyHu** [comment]
It has been solved, thank you for your answer.

**Comment by xinntao** [comment]
@iMartyn Sorry for that...

We choose to close the issue because:
we will upgrade MMSR to MMEditing (in the same repo), which consists of SR, inpainting, matting and generation tasks. 
And MMSR will be deprecated and no longer exist.

For your question,

I have tried on my windows, it seems OK.
```
MINGW64 ~/Documents/Work
$ git clone git@github.com:open-mmlab/mmsr.git
Cloning into 'mmsr'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 162 (delta 3), reused 0 (delta 0), pack-reused 153
Receiving objects: 100% (162/162), 103.11 KiB | 226.00 KiB/s, done.
Resolving deltas: 100% (60/60), done.
```
And this is my git version
```
$  git version
git version 2.24.0.windows.2
```

**Comment by iMartyn** [comment]
Unfortunately not for me, windows 10 not mingw, git from [git-scm's installer](https://git-scm.com/download/win).  Same is true via the git gui.  Still broken.  It's the `.` at the end of the folder I'm pretty sure.

```
C:\Users\Martyn\Documents\src\github.com\open-mmlab>git version
git version 2.26.2.windows.1

C:\Users\Martyn\Documents\src\github.com\open-mmlab>git clone https://github.com/open-mmlab/mmsr.git
Cloning into 'mmsr'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 162 (delta 3), reused 0 (delta 0), pack-reused 153
Receiving objects: 100% (162/162), 103.11 KiB | 306.00 KiB/s, done.
Resolving deltas: 100% (60/60), done.
error: invalid path 'experiments/pretrained_models/Put pretrained models here.'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

C:\Users\Martyn\Documents\src\github.com\open-mmlab>rm -rf mmsr

C:\Users\Martyn\Documents\src\github.com\open-mmlab>git clone git@github.com:open-mmlab/mmsr.git
Cloning into 'mmsr'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 162 (delta 3), reused 0 (delta 0), pack-reused 153
Receiving objects: 100% (162/162), 103.11 KiB | 201.00 KiB/s, done.
Resolving deltas: 100% (60/60), done.
error: invalid path 'experiments/pretrained_models/Put pretrained models here.'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by xinntao** [comment]
@iMartyn Thanks~
We will remove the `.` at the end of the folder~

**Comment by xinntao** [comment]
Hi @iMartyn 
We update this repo~ The `mmsr` has been merged into this `mmedting` repo. So I am going to close this issue because `mmsr` does not exist anymore.  

We have checked there is no `.` at the end of the folders. So hope it can be cloned in Windows~

**Comment by VanessaOlago** [comment]
These commands worked for me, I had a similar issue 
git reset
git config core.protectNTFS false
git checkout
